title: "Carlos Nascimento"
description: "Documentando estudos, labs e reflexões técnicas."
url: "https://github.com/carloskyle" # troque depois
timezone: America/Sao_Paulo

markdown: kramdown
kramdown:
  input: GFM

permalink: /:categories/:year/:month/:day/:title/

# Deixa o GitHub Pages feliz
plugins:
  - jekyll-feed

# Dados usados no "Sobre"
author:
  name: "Carlos Nascimento"
  role: "Network/Security • CTF • Aprendizado contínuo"
  bio: "Escrevo sobre o que estudo: redes, segurança, soluções e troubleshooting."
  links:
    github: "https://github.com/carloskyle"

    linkedin: "https://www.linkedin.com/in/carlos-nascimento-673741188/"
