title: "carloskyle"
description: "estudos, CTFs e etc!"
url: "https://carloskyle.github.io/"
timezone: America/Sao_Paulo

markdown: kramdown
kramdown:
  input: GFM

permalink: /:categories/:year/:month/:day/:title/


plugins:
  - jekyll-feed

author:
  name: "Carlos Nascimento"
  role: "IT Analyst N2 | Network Security | CTF"
  bio: "Olá, meu nome é Carlos e tenho uma paixão enorme pela tecnologia desde pequeno, finalizei minha faculdade de Segurança da Informação e estou iniciando minha carreira desbravando o mundo da tecnologia, no momento tenho atuado em aprendizados em Redes, Segurança Ofensiva e Defensiva!"
  <br>
  bio: teste
  <br>
  bio: teste




  links:
    github: "https://github.com/carloskyle"

    linkedin: "https://www.linkedin.com/in/carlos-nascimento-673741188/"




