title: "carloskyle"
description: "estudos, CTFs e etc!"
url: "https://carloskyle.github.io/"
timezone: America/Sao_Paulo

markdown: kramdown
kramdown:
  input: GFM

permalink: /:categories/:year/:month/:day/:title/


plugins:
  - jekyll-feed

author:
  name: "Carlos Nascimento"
  role: "IT Analyst N2 | Network Security | CTF"
  bio: "Olá! Meu nome é Carlos e trabalho como Analista de TI (N2), dando suporte a projetos relacionados à infraestrutura de rede e cibersegurança, Auxilio em implementações, configurações e resolução de problemas, principalmente envolvendo soluções de firewall e ambientes de rede seguros. Tenho especial interesse em segurança de redes e em como os sistemas se comunicam e se mantêm protegidos, Estou trilhando meu caminho para me tornar um excelente profissional na área de Segurança e Redes e busco constantemente aprimorar minhas habilidades técnicas por meio da experiência prática."




  links:
    github: "https://github.com/carloskyle"

    linkedin: "https://www.linkedin.com/in/carlos-nascimento-673741188/"



